---
- hosts: all
  sudo: yes
  gather_facts: no


  vars:
    home: /opt/akl.lt
    path: "{{ home }}/app"
    install: false


  tasks:

  - fail: msg="Ansible version 1.6 or greater required."
    when: "ansible_version.full | version_compare('1.6', '<')"

  - name: update locale
    locale_gen: name=en_US.UTF-8 state=present
    when: install

  - name: apt packages
    apt: pkg={{ item }} state=latest
    with_items:
    - build-essential
    - python-dev
    - python-pip
    - supervisor
    - nginx
    - git
    when: install

  - name: install uwsgi
    apt: pkg={{ item }} state=latest
    with_items:
    - uwsgi
    - uwsgi-plugin-python3
    notify: restart uwsgi
    when: install

  - name: create akl user
    user: name=akl system=yes group=www-data home={{ home }}
    when: install

  - name: clone repository
    git: repo=https://github.com/python-dirbtuves/akl.lt.git dest={{ path }} force=yes
    sudo_user: akl
    notify: gracefully reload uwsgi

  - name: create directories
    file: path={{ path }}/{{ item }} state=directory
    with_items:
      - var/run
      - var/log
      - var/www/media
      - parts/uwsgi
    sudo_user: akl
    when: install

  - name: install app dependencies
    command: make ubuntu chdir={{ path }}
    sudo: yes
    when: install

  - name: init buildout
    template: src=buildout.cfg dest={{ path }}/buildout.cfg

  - name: build project
    command: make chdir={{ path }}
    sudo_user: akl

  - name: setup uwsgi
    template: src=uwsgi.ini dest={{ path }}/parts/uwsgi/uwsgi.ini
    notify: restart uwsgi

  - name: setup supervisor
    template: src=supervisor.conf dest=/etc/supervisor/conf.d/akllt.conf
    notify: restart supervisor

  - name: setup nginx
    template: src=nginx.conf dest=/etc/nginx/sites-enabled/akl.lt.conf
    notify: restart nginx

  - name: nginx configtest
    # `service nginx configtest` always return 0 exit code
    command: nginx -t -c /etc/nginx/nginx.conf
    tags: [debug]


  handlers:

  - name: gracefully reload uwsgi
    shell: kill -HUP $(supervisorctl pid akllt-uwsgi)

  - name: restart uwsgi
    supervisorctl: name=akllt-uwsgi state=restarted

  - name: restart supervisor
    service: name=supervisor state=restarted

  - name: restart nginx
    service: name=nginx state=restarted
